jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run MD to PDF
        uses: ./.github/actions/md-to-pdf
        with: 
          input_path: ./docs/readme.md
